# Generated by Django 5.1.2 on 2024-10-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_tool', models.ImageField(upload_to='intro_pictures/%Y/%m/%d', verbose_name='Обложка')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('price_ym', models.IntegerField(verbose_name='Цена яндекс маркет')),
                ('price_ozon', models.IntegerField(verbose_name='Цена ozon')),
                ('price_wb', models.IntegerField(verbose_name='Цена вб')),
                ('url_ym', models.URLField(verbose_name='url яндекс маркет')),
                ('url_ozon', models.URLField(verbose_name='url ozon')),
                ('url_wb', models.URLField(verbose_name='url wb')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Интсрумент',
                'verbose_name_plural': 'Инструменты',
                'ordering': ['-created_at'],
            },
        ),
    ]
